# Site settings
title: Undoprototipos
email: info@undoprototipos.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.undoprototipos.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: undo.prototipos

paginate: 1

# Build settings
markdown: kramdown

# Colecciones
collections:
  aplicaciones:
    output: true
    permalink: /aplicaciones/:path/
  materiales:
    output: true
    permalink: /materiales/:path/
  sectores:
    output: true
    permalink: /sectores/:path/
  tecnologias:
    output: true
    permalink: /tecnologías/:path/
  slides:

defaults:
  - scope:
      path: ""
      type: aplicaciones
    values:
      layout: collection-item
  - scope:
      path: ""
      type: materiales
    values:
      layout: collection-item
  - scope:
      path: ""
      type: sectores
    values:
      layout: collection-item
  - scope:
      path: ""
      type: tecnologias
    values:
      layout: collection-item
